

export const PRODUCT_LIST = "PRODUCT_LIST"
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST"
export const PRODUCT_INSERT_LIST = "PRODUCT_INSERT_LIST"
export const INSERT_DATA_SUCCSESS = "INSERT_DATA_SUCCSESS"
export const INSERT_DATA_FAILD = "INSERT_DATA_FAILD"
export const PRODUCT_UPDATE_LIST = "PRODUCT_UPDATE_LIST"
export const UPDATE_DATA_SUCCSESS = "UPDATE_DATA_SUCCSESS"
export const UPDATE_DATA_FAILD = "UPDATE_DATA_FAILD"
export const EDIT_FORM_DATA = "EDIT_FORM_DATA"
export const SET_EDIT_FORM_DATA = "SET_EDIT_FORM_DATA"



export const PRODUCT_NAME_GET_LIST = "PRODUCT_NAME_GET_LIST"
export const SET_PRODUCT_NAME_GET_LIST = "SET_PRODUCT_NAME_GET_LIST"

export const PRODUCT_TYPE_GET_LIST = "PRODUCT_TYPE_GET_LIST"
export const SET_PRODUCT_TYPE_GET_LIST = "SET_PRODUCT_TYPE_GET_LIST"

export const SUPPLIER_GET_LIST = "SUPPLIER_GET_LIST"
export const SET_SUPPLIER_GET_LIST = "SET_SUPPLIER_GET_LIST"