

export const PRODUCT_LIST = "PRODUCT_LIST"
export const SET_PRODUCT_LIST = "SET_PRODUCT_LIST"
export const PRODUCT_INSERT_LIST = "PRODUCT_INSERT_LIST"

export const PRODUCT_NAME_GET_LIST = "PRODUCT_NAME_GET_LIST"
export const SET_PRODUCT_NAME_GET_LIST = "SET_PRODUCT_NAME_GET_LIST"

export const PRODUCT_TYPE_GET_LIST = "PRODUCT_TYPE_GET_LIST"
export const SET_PRODUCT_TYPE_GET_LIST = "SET_PRODUCT_TYPE_GET_LIST"

export const SUPPLIER_GET_LIST = "SUPPLIER_GET_LIST"
export const SET_SUPPLIER_GET_LIST = "SET_SUPPLIER_GET_LIST"